apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    type: Opaque
    metadata:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
  encryptedData:
    WG_WIREGUARD_PRIVATE_KEY: {{ .Values.WG_WIREGUARD_PRIVATE_KEY }}
    SHADOWSOCKS_PASSWORD: {{ .Values.SHADOWSOCKS_PASSWORD }}
